sudo: required
services:
  - docker
before_install:
  - docker pull nimlang/nim
script:
  - docker run nimlang/nim nim --version
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble install -y && nimble test"
  - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble coverage"